### ISSUE TITLE
FOG: Too much information

### ISSUE THREAD

**Issue by renebaudisch** [cschleiden/imperaplus-client#17]
Spiel Id 14 
Ich dürfte den letzten Zug nicht sehen, nach Verlust von Mexiko habe ich keine Länder mehr neben Belize
![image](https://cloud.githubusercontent.com/assets/15980546/25757439/c82ef844-31ca-11e7-8fa3-6004571c7017.png)

**Comment by cschleiden** [comment]
Wenn du waehrend des Zugs die ganze Zeit refresht haettest, haettest du es aber verfolgen koennen, oder?

**Comment by renebaudisch** [comment]
Na OK, ich hätte sehen können, dass 18 Einheiten von Mexiko weg irgendwo angegriffen haben, da mir der Flughafen MEX noch gehörte, aber zum Zielland hatte ich keine Connection mehr.

Hier ein Screen, Bot in rot
![image](https://cloud.githubusercontent.com/assets/15980546/25772494/82d99c48-326c-11e7-84a4-badb0db2d5c0.png)

**Comment by renebaudisch** [comment]
Anderes Beispiel. https://dev.imperaonline.de/play/22/history/6
Ich kann anhand der History drei Länder erkennen, die der Bot besetzt, obwohl ich diese gar nicht sehen kann, Ich denke, das ist irgendwie auch Ansichtssache. Sehe ich, wenn ich ein Land sehe auch, von wo es angegriffen wurde...

![image](https://cloud.githubusercontent.com/assets/15980546/25772539/fa1c7310-326d-11e7-8918-34acbc023176.png)

**Comment by cschleiden** [comment]
Hm hm.. ja, ich nehme den Stand des vorherigen Zugs und wenn eines der Laender sichtbar ist, siehst du die Aktion, ansonsten eben nicht. Vielleicht wuerde es Sinn machen, das noch weiter runter zu brechen, also auch partielle Aktionen zu unterstuetzen.. "Land X wurde angegriffen"

**Comment by cschleiden** [comment]
Achso, in dem Fall, waehrend des Zuges konntest du die Laender sehen, daher sind die in der History sichtbar. Staendiges refreshen sollte dir keinen Vorteil verschaffen, daher haben wir damals entschieden diese Zuege einfach komplett zu zeigen.
