### ISSUE TITLE
Too small unit field and overlapping for unit values greater > 9999

### ISSUE THREAD

**Issue by renebaudisch** [cschleiden/imperaplus-client#18]
Place units:
![image](https://cloud.githubusercontent.com/assets/15980546/25761877/aa6594f0-31dc-11e7-9bc7-a42d4b790034.png)

Attack/Move
![image](https://cloud.githubusercontent.com/assets/15980546/25761780/4fafce36-31dc-11e7-850e-753731284881.png)

**Comment by cschleiden** [comment]
Ich weiss nicht ob ich dafuer optimieren moechte :)

**Comment by renebaudisch** [comment]
EXTREME Testing :)
