### ISSUE TITLE
Same player colour

### ISSUE THREAD

**Issue by renebaudisch** [cschleiden/imperaplus-client#19]
Ich kann ein von mir erstelltes Spiel verlassen, das ging vorher nicht. Zwischendurch bist du beigetreten und ich gerade eben auch wieder, jedoch haben wir nun beide die Farbe "Blau"

![image](https://cloud.githubusercontent.com/assets/15980546/25802212/976fa928-33f1-11e7-8f81-8f01f4d248eb.png)

Eventuell ist das Verlassen nicht zu erlauben die einfachste Lösung?

**Comment by cschleiden** [comment]
Oh ja, das ist definitiv ein bug.
