### ISSUE TITLE
Mini map missing

### ISSUE THREAD

**Issue by renebaudisch** [cschleiden/imperaplus-client#28]
is needed on huge cards to navigate on tablet and smartphone

**Comment by cschleiden** [comment]
Bin mir nicht sicher... War damals interessant zu bauen, aber ich weiss nicht ob es die wert war.

**Comment by renebaudisch** [comment]
Spiel die Air Ocean World mal auf dem Handy, das geht nicht du kannst weit entfernte Gebiete nicht angreifen...

**Comment by cschleiden** [comment]
Aber du kannst die Karte selber scrollen?

**Comment by renebaudisch** [comment]
Eben nicht, Da dann das Land von dem Angegriffen wird nicht ausgewählt bleibt.

**Comment by cschleiden** [comment]
Ah.. das ist dann vielleicht eher der Bug :)

**Comment by renebaudisch** [comment]
Oder so :)
Aber man muss das Land ja auch wieder abwählen können, aber ggf. reicht ja ein prevent.default auf den Touchevents

**Comment by cschleiden** [comment]
Welches phone? iPhone?
