### ISSUE TITLE
neighbouring countries visibility error after attack

### ISSUE THREAD

**Issue by alpentrio** [cschleiden/imperaplus-client#29]
After attack ends with 1 unit, units of neighbouring countries are not longer visible.
Move 10:
![2017-09-24-spiel-790 - groups 16-alpentrio-lordzwenkau-1-zug-10-anzeige-pennsylvania-ok](https://user-images.githubusercontent.com/32242233/30783553-0b80e898-a145-11e7-8884-a377e0f60c0f.JPG)
Move 12 after attack ends mit one 1 unit at Pennsyvania:
![2017-09-24-spiel-790 - groups 16-alpentrio-lordzwenkau-1-zug-12-anzeigefehler-pennsylvania](https://user-images.githubusercontent.com/32242233/30783554-0b812772-a145-11e7-9d31-5436dadcf437.JPG)
If the move (here 12) is ended, the neighbouring countries are displayed correct.

**Comment by cschleiden** [comment]
Ah great thx for the repro. I've seen this before but wasn't really able to reproduce. I'll check

**Comment by cschleiden** [comment]
Found the root cause, fixing right now.

**Comment by cschleiden** [comment]
Fixed.
