### ISSUE TITLE
Neue Runde bei Turnieren startet nicht

### ISSUE THREAD

**Issue by sunseeker-IO** [cschleiden/imperaplus-client#47]
In den letzten Wochen stürzt fast jedes zweite Turnier ab. Allen Abstürzen gemeinsam ist, dass die angefangene Runde zu Ende gespielt werden kann, nach Beendigung aller Spiele die neue Runde aber nicht startet. Es gab Turniere bei denen ein Spieleraccount gelöscht war, evtl. hat das den Start der nächsten Runde verhindert. Ich kann dies aber nicht als alleinigen Grund verifizieren. 
Im Augenblick gibt es noch ein nicht gelöschtes Turnier, das in den letzten Tagen abgestürzt ist: Turnier: Österreich - IWT Saison 2

![IWT Österreich1](https://user-images.githubusercontent.com/59518508/74615631-e4f1a100-5122-11ea-8b0a-600674e8b33a.JPG)

![IWT Österreich](https://user-images.githubusercontent.com/59518508/74615609-c2f81e80-5122-11ea-9af7-db0100caf116.JPG)

Vielleicht kannst Du bei abgestürzten Turnieren einen Start der nächsten Runde erzwingen.

**Comment by renebaudisch** [comment]
Fehlermeldung lt. Forum:

> Ungelesener Beitrag von ra.nowack » Mo Jan 14, 2019 10:23 am
> Für die Profis - mir ist gerade im Adminbereich eine Fehlermeldung in die Hände gefallen. Diese erscheint immer, wenn ich ein bereits beendetes Turnier löschen will (wollte mal die IWT - Turniere rausnehmen) und lautet:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to save changes because a circular dependency was detected in the data to be saved: 'ForeignKey: Tournament.WinnerId -> TournamentTeam.Id Unique ToPrincipal: Winner, ForeignKey: TournamentTeam.TournamentId -> Tournament.Id ToDependent: Teams ToPrincipal: Tournament'.
Microsoft.EntityFrameworkCore.Internal.Multigraph.BatchingTopologicalSort(Func>>, string> formatCycle)
Stack Query Cookies Headers
```

**Comment by sunseeker-IO** [comment]
genosse27 hat mir gerade ein Foto des TournamentJobs geschickt
https://cdn.discordapp.com/attachments/604064976382066691/687823240462467163/unknown.png
![TournamentJob](https://user-images.githubusercontent.com/59518508/76580217-727ca280-64cf-11ea-8094-992d4c104bfe.png)

im oberen Teil sind die laufenden Turniere.
die unteren Zeilen mit Starting next Round betreffen alle abgestürzte Turniere, d.h. das System erkennt, dass es eine neue Runde starten soll, tut es aber nicht

**Comment by renebaudisch** [comment]
Dann wird das wohl hier sitzen:
https://github.com/cschleiden/imperaplus-backend/blob/43a882c824120cebdfe2338e90c1b315e573246c/ImperaPlus.Domain/Services/TournamentService.cs

**Comment by cschleiden** [comment]
Habe die Turniere manuell gefixt.
