### ISSUE TITLE
Rechte zum Erstellen von Turnieren

### ISSUE THREAD

**Issue by sunseeker-IO** [cschleiden/imperaplus-client#48]
Leider hat der admin der IWT ra.nowack aus Frust über die ständig abstürzenden Turniere seinen Spieleraccount gelöscht. Es gibt nun keinen aktiven Spieler mehr, der Turniere erstellen kann. genosse27 kann dies, ist aber nur noch selten online. Kannst Du mir oder einem anderen Spieler deines Vertrauens diese Rechte einräumen?

**Comment by cschleiden** [comment]
Jap, done!
